apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/app

patches:
  # project
  - patch: |-
      - op: replace
        path: /metadata/name
        value: stg-argocd
    target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject

  # application
  - patch: |-
      - op: replace
        path: /metadata/name
        value: stg-argocd
      - op: replace
        path: /spec/project
        value: stg-argocd
      - op: replace
        path: /spec/source/path
        value: argocd/generated/stg
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
