apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ns.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.9
  # - install.yaml
  # - sealed-argocd-secret.yaml
patches:
  # - argocd-secret.yaml
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
patchesStrategicMerge:
  - argocd-server.yaml
