apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgBMbHDUKZhyPktqNZihRYTkgoS3mbenXGMeoUlUKF2s9+8+jSOkMInZAtLis+2mF/P74VJC5UePOPdwmeo+26YSx+td2EYqmQUbxvAZWdOhyzZ7YwjrnisVZ7XBYix5QavkoSvQvZUMzPKWAzXhDusMh2iVhghwGueVjJx9ZtQ43lxjWCs6DVotAUnh1P1IwVAVdvyTzCyQNH3YxvinDs8sHmHNGQnnC0ss8XtByiT0PxZ7KL/Tk/dQ9U0/QxEMPhDHz5buJxGhtJ0J/EI4BSLkjFoa9K5Ivycs+ohgKRUz01qXpxhhd28Xm8h5ARsytu0dBZdw7I6AecofCjlVRFmPDG1OanGBet9RxDdL2SHWsaAAdOMvMTBvPNhRHnKAvH7yBdiFtQJqRciBbqqKUwaG+Za3UwB8kmIs8frUtX8zmGX4xFxD6oLvQwh+ahuGLodVwa1m1i2kJ1plfgwoxOVHPItmeaC+5Nk9MqUPZZvqlqOtm9OtE1O2elAd4lA2N6CygG72mOu167Gkj+gcCVTz7vnoKtgEfC9MnCCF6BgP5MX8DCOuI3Tt33+Ths7l1HytbChVo8OA0pM3xfw+hqr05TxNu71zqT6R2Jp1/md1x0F3zA2WNbustfcMXX/LABd05sNfyblotRAWw5gkLAGfZs8Pn6hkMff8q754IEGvi5td//pp6hdxk524iYKScoE/vtghrUaE+TM=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
