apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgCM+HxEy23JUgaq1vvzOYpI4dVnK7+vXF0ujp9rom0ez9Sxi00Esn4iCkO03Bo5FXDVMSdxocley+Li4MjvieZO5Jgq11OiFr2Y8AmhmBypuDhGDwl5UfIJdXvIeMVcOCOd5vI0MVGQWaaUL+LgJX9G2Ts2dgE4rrB891HvWx7MXtbcRzqJMrMKQMvYxbqsPSrL26ICLjvSBKJ2TJ99K7ihIIT738fWvjpOl/qkvYbwQIO0pXqn+4/J1oGBOHxmMOGUow3kFySfzftqF1Svwql/BIudUdlmFEmU869znTeBks3mbell//wTQDpunL5bWIoJCXYGq0Lop3O5Qg9xnTu3lZRIYFMDs3Aox7kb9P+YbHusrmdcVb2pTi2ZvSTwKDwXgRWC3zDOq3Kik6qapxPVkWviD8EVWMMCaC/BoDj9ORWtT6IxECNhekELTJUmg++IX+wtAAK99s1pIaeyZKG5fY5k8JsmdJFawEGrAd6TdDsSs7tPgrNUOmUa4t/NkE2TxlXtVEPwdAGF7SEyN+8wtqBw3GXcgfTXmUvf1ghYONGxdTq2L8sPjH6DqZhrhagv0Mgmf/9+isP/xBAO/slgZ3ExaWk3q3KT86YxvAthsTL18c07tkwUKteZAijM5DGdhlaRjm+JTSaLDwwwe8/hgqo5pYNVyzyNvd8AdRm/B5XyHsF79R1Tc1nnpomkJgHm3M/0H6rhs8x5
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
