apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  labels:
    name: argocd
spec:
  project: default # argocd
  source:
    repoURL: https://github.com/Himalayan-wildcat/argocd-test.git
    targetRevision: HEAD
    path: argocd/generated
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - ServerSideApply=true
    - Validate=true
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 1
