apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  description: argocd
  sourceRepos:
  - https://github.com/Himalayan-wildcat/argocd-test.git
  destinations:
  - namespace: argocd
    server: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
  orphanedResources:
    warn: true
