apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-multiroute
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Himalayan-wildcat/argocd-test
    targetRevision: main
    path: manifests/argo-rollouts/bluegreen/multiroute
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/selector/rollouts-pod-template-hash
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
