apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: app1
  name: stg-app1
  namespace: argocd
spec:
  destination:
    namespace: app1
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    kind: Deployment
    namespace: app1
  project: default
  revisionHistoryLimit: 10
  source:
    directory:
      recurse: true
    path: app1/generated/stg
    repoURL: https://github.com/Himalayan-wildcat/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - ServerSideApply=true
    - Validate=true
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
