apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  labels:
    name: app1
spec:
  project: app1
  source:
    repoURL: git@github.com:Nextremer/argocd-test.git
    targetRevision: HEAD
    path: app1/generated/stg
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - ServerSideApply=true
    - Validate=true
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  revisionHistoryLimit: 10
