apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app1
spec:
  description: app1
  sourceRepos:
  - git@github.com:Nextremer/argocd-test.git
  destinations:
  - namespace: "*"
    server: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
  orphanedResources:
    warn: true
