apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/install
patches:
  # deployment: applicationset-controller
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=argocd-applicationset-controller"

  # deployment: argoc-dex-server
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=argocd-dex-server"
