apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: argocd
  name: stg-argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 1
  source:
    directory:
      recurse: true
    path: argocd/generated/stg
    repoURL: https://github.com/Himalayan-wildcat/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - ServerSideApply=true
    - Validate=true
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
