apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stg-argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: argocd
  destinations:
  - namespace: argocd
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
  - git@github.com:Nextremer/argocd-test.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: argocd
  name: stg-argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
    server: https://kubernetes.default.svc
  project: stg-argocd
  revisionHistoryLimit: 10
  source:
    directory:
      recurse: true
    path: argocd/generated/stg
    repoURL: git@github.com:Nextremer/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - ServerSideApply=true
    - Validate=true
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
